### ISSUE TITLE
cocoapods导入以后 运行就奔溃 报这个错误

### ISSUE THREAD

**Issue by GPX-NSlog** [wangrui460/WRNavigationBar#62]
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Please file a radar on UIKit with this log if you see this assertion. selectorString = wr_setTitleTextAttributes:, exercisedImplementations = {
    "setBarTintColor:" =     (
    );
    "setTintColor:" =     (
    );
    "setTitleTextAttributes:" =     (
    );
    "wr_setTitleTextAttributes:" =     (
    );
}'

**Comment by wangrui460** [comment]
我试了一下，没有问题~

**Comment by liyunhe** [comment]
遇到一样的错误

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Please file a radar on UIKit with this log if you see this assertion. selectorString = wr_setTitleTextAttributes:, exercisedImplementations = {
"setBarTintColor:" = (
);
"setTintColor:" = (
);
"setTitleTextAttributes:" = (
);
"wr_setTitleTextAttributes:" = (
);
}'
